[book]
title = "ClaraX user guide"
description = "ClaraX user guide"
authors = ["Abdulwahed Mansour"]

[preprocessor.pyo3_version]
command = "python3 pyo3_version.py"

[preprocessor.glossary_linker]
command = "python3 glossary_linker.py"

[preprocessor.tabs]

[output.html]
git-repository-url = "https://github.com/abdulwahed-sweden/clarax/tree/main/guide"
edit-url-template = "https://github.com/abdulwahed-sweden/clarax/edit/main/guide/{path}"
playground.runnable = false
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
